// GENERATED by `npm run db:types` from the local database (all migrations applied).
// Don't edit by hand: change a migration, then regenerate. Overrides live in database.ts.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_participants: {
        Row: {
          accepted: boolean
          cleared_at: string | null
          conversation_id: string
          joined_at: string
          last_read_at: string
          marked_unread: boolean
          muted: boolean
          pinned_at: string | null
          role: string
          user_id: string
          wallpaper: string | null
        }
        Insert: {
          accepted?: boolean
          cleared_at?: string | null
          conversation_id: string
          joined_at?: string
          last_read_at?: string
          marked_unread?: boolean
          muted?: boolean
          pinned_at?: string | null
          role?: string
          user_id: string
          wallpaper?: string | null
        }
        Update: {
          accepted?: boolean
          cleared_at?: string | null
          conversation_id?: string
          joined_at?: string
          last_read_at?: string
          marked_unread?: boolean
          muted?: boolean
          pinned_at?: string | null
          role?: string
          user_id?: string
          wallpaper?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversation_participants_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_participants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          avatar_url: string | null
          created_at: string
          created_by: string | null
          description: string | null
          direct_key: string | null
          id: string
          invite_code: string | null
          is_group: boolean
          last_message_at: string | null
          name: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          direct_key?: string | null
          id?: string
          invite_code?: string | null
          is_group?: boolean
          last_message_at?: string | null
          name?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          direct_key?: string | null
          id?: string
          invite_code?: string | null
          is_group?: boolean
          last_message_at?: string | null
          name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      friendships: {
        Row: {
          addressee_id: string
          created_at: string
          id: string
          requester_id: string
          responded_at: string | null
          status: string
        }
        Insert: {
          addressee_id: string
          created_at?: string
          id?: string
          requester_id: string
          responded_at?: string | null
          status?: string
        }
        Update: {
          addressee_id?: string
          created_at?: string
          id?: string
          requester_id?: string
          responded_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "friendships_addressee_id_fkey"
            columns: ["addressee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friendships_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      link_previews: {
        Row: {
          description: string | null
          fetched_at: string
          site_name: string | null
          title: string | null
          url: string
        }
        Insert: {
          description?: string | null
          fetched_at?: string
          site_name?: string | null
          title?: string | null
          url: string
        }
        Update: {
          description?: string | null
          fetched_at?: string
          site_name?: string | null
          title?: string | null
          url?: string
        }
        Relationships: []
      }
      message_reactions: {
        Row: {
          created_at: string
          emoji: string
          message_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          emoji: string
          message_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          emoji?: string
          message_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "message_reactions_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "message_reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          attachment: Json | null
          content: string | null
          conversation_id: string
          created_at: string
          deleted_at: string | null
          edited_at: string | null
          id: string
          image_path: string | null
          kind: string
          mentions: string[]
          pinned_at: string | null
          pinned_by: string | null
          reply_to_id: string | null
          sender_id: string
        }
        Insert: {
          attachment?: Json | null
          content?: string | null
          conversation_id: string
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          image_path?: string | null
          kind?: string
          mentions?: string[]
          pinned_at?: string | null
          pinned_by?: string | null
          reply_to_id?: string | null
          sender_id?: string
        }
        Update: {
          attachment?: Json | null
          content?: string | null
          conversation_id?: string
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          image_path?: string | null
          kind?: string
          mentions?: string[]
          pinned_at?: string | null
          pinned_by?: string | null
          reply_to_id?: string | null
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_pinned_by_fkey"
            columns: ["pinned_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_reply_to_id_fkey"
            columns: ["reply_to_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          full_name: string
          id: string
          last_seen_at: string
          presence_visibility: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          full_name: string
          id: string
          last_seen_at?: string
          presence_visibility?: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string
          id?: string
          last_seen_at?: string
          presence_visibility?: string
          username?: string
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          details: string | null
          id: string
          message_content: string | null
          message_id: string | null
          reason: string
          reported_user_id: string
          reporter_id: string
        }
        Insert: {
          created_at?: string
          details?: string | null
          id?: string
          message_content?: string | null
          message_id?: string | null
          reason: string
          reported_user_id: string
          reporter_id: string
        }
        Update: {
          created_at?: string
          details?: string | null
          id?: string
          message_content?: string | null
          message_id?: string | null
          reason?: string
          reported_user_id?: string
          reporter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_user_id_fkey"
            columns: ["reported_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_messages: {
        Row: {
          created_at: string
          message_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          message_id: string
          user_id?: string
        }
        Update: {
          created_at?: string
          message_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_messages_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_messages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_message_request: { Args: { conv_id: string }; Returns: undefined }
      add_group_members: {
        Args: { conv_id: string; member_ids: string[] }
        Returns: undefined
      }
      are_friends: { Args: { a: string; b: string }; Returns: boolean }
      block_user: { Args: { target_id: string }; Returns: undefined }
      can_add_to_group: { Args: { member: string }; Returns: boolean }
      can_see_profile: { Args: { target: string }; Returns: boolean }
      can_send_to: { Args: { conv_id: string }; Returns: boolean }
      clear_conversation: { Args: { conv_id: string }; Returns: undefined }
      create_group_conversation: {
        Args: { group_name: string; member_ids: string[] }
        Returns: string
      }
      delete_message: { Args: { msg_id: string }; Returns: undefined }
      delete_push_subscription: {
        Args: { sub_endpoint: string }
        Returns: undefined
      }
      edit_message: {
        Args: { msg_id: string; new_content: string }
        Returns: undefined
      }
      get_blocked_conversations: { Args: never; Returns: string[] }
      get_group_invite: {
        Args: { code: string }
        Returns: {
          already_member: boolean
          avatar_url: string
          conversation_id: string
          description: string
          member_count: number
          name: string
        }[]
      }
      get_my_blocks: {
        Args: never
        Returns: {
          avatar_url: string
          created_at: string
          full_name: string
          user_id: string
          username: string
        }[]
      }
      get_my_conversations: {
        Args: never
        Returns: {
          avatar_url: string
          cleared_at: string
          created_at: string
          description: string
          id: string
          invite_code: string
          is_group: boolean
          is_request: boolean
          last_message: Json
          last_message_at: string
          last_read_at: string
          marked_unread: boolean
          members: Json
          muted: boolean
          my_role: string
          name: string
          pinned_at: string
          unread_count: number
          wallpaper: string
        }[]
      }
      get_my_friendships: {
        Args: never
        Returns: {
          avatar_url: string
          created_at: string
          direction: string
          full_name: string
          status: string
          user_id: string
          username: string
        }[]
      }
      get_or_create_direct_conversation: {
        Args: { other_user_id: string }
        Returns: string
      }
      is_allowed_avatar_url: {
        Args: { folder: string; url: string }
        Returns: boolean
      }
      is_blocked_between: { Args: { a: string; b: string }; Returns: boolean }
      is_group_admin: { Args: { conv_id: string }; Returns: boolean }
      is_group_admin_of_path: {
        Args: { object_name: string }
        Returns: boolean
      }
      is_member: { Args: { conv_id: string }; Returns: boolean }
      is_member_of_path: { Args: { object_name: string }; Returns: boolean }
      is_member_of_topic: { Args: { topic: string }; Returns: boolean }
      is_message_request: {
        Args: { conv_id: string; uid: string }
        Returns: boolean
      }
      is_request_for_me: { Args: { conv_id: string }; Returns: boolean }
      is_username_available: { Args: { name: string }; Returns: boolean }
      is_valid_attachment: { Args: { a: Json; kind: string }; Returns: boolean }
      join_group_by_invite: { Args: { code: string }; Returns: string }
      leave_conversation: { Args: { conv_id: string }; Returns: undefined }
      mark_conversation_read: { Args: { conv_id: string }; Returns: undefined }
      mark_conversation_unread: {
        Args: { conv_id: string }
        Returns: undefined
      }
      orphaned_files: {
        Args: { max_rows?: number }
        Returns: {
          bucket_id: string
          name: string
        }[]
      }
      people_you_may_know: {
        Args: never
        Returns: {
          avatar_url: string
          full_name: string
          id: string
          mutual_friends: number
          username: string
        }[]
      }
      pin_message: {
        Args: { msg_id: string; pinned: boolean }
        Returns: undefined
      }
      push_recipients: {
        Args: { conv_id: string; mentioned?: string[]; sender: string }
        Returns: string[]
      }
      react: { Args: { emoji: string; msg_id: string }; Returns: undefined }
      remove_friendship: { Args: { other_user_id: string }; Returns: undefined }
      remove_group_member: {
        Args: { conv_id: string; member_id: string }
        Returns: undefined
      }
      report: {
        Args: {
          details?: string
          msg_id: string
          reason: string
          target_user: string
        }
        Returns: undefined
      }
      respond_friend_request: {
        Args: { accept: boolean; requester: string }
        Returns: undefined
      }
      save_push_subscription: {
        Args: {
          sub_auth: string
          sub_endpoint: string
          sub_p256dh: string
          sub_user_agent: string
        }
        Returns: undefined
      }
      search_messages: {
        Args: { conv_id?: string; query: string }
        Returns: {
          content: string
          conversation_id: string
          created_at: string
          id: string
          sender_id: string
        }[]
      }
      search_people: {
        Args: { handle: string }
        Returns: {
          avatar_url: string
          full_name: string
          id: string
          username: string
        }[]
      }
      send_friend_request: { Args: { target_id: string }; Returns: string }
      send_to_members: {
        Args: { conv_id: string; event: string; payload: Json; skip?: string }
        Returns: undefined
      }
      send_to_user: {
        Args: { event: string; payload: Json; uid: string }
        Returns: undefined
      }
      set_conversation_muted: {
        Args: { conv_id: string; is_muted: boolean }
        Returns: undefined
      }
      set_conversation_pinned: {
        Args: { conv_id: string; pinned: boolean }
        Returns: undefined
      }
      set_conversation_wallpaper: {
        Args: { conv_id: string; new_wallpaper: string }
        Returns: undefined
      }
      set_group_description: {
        Args: { conv_id: string; new_description: string }
        Returns: undefined
      }
      set_group_invite: {
        Args: { conv_id: string; enabled: boolean }
        Returns: string
      }
      set_member_role: {
        Args: { conv_id: string; member_id: string; new_role: string }
        Returns: undefined
      }
      touch_last_seen: { Args: never; Returns: undefined }
      unblock_user: { Args: { target_id: string }; Returns: undefined }
      update_group: {
        Args: { conv_id: string; new_avatar_url: string; new_name: string }
        Returns: undefined
      }
      visible_last_seen: { Args: { target: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

