// Finishes `npm run db:types`: adds the "generated" note on top of the fresh types.
import { readFileSync, renameSync, writeFileSync } from 'node:fs'

const TMP = 'src/types/database.generated.ts.tmp'
const OUT = 'src/types/database.generated.ts'
const note = `// GENERATED by \`npm run db:types\` from the local database (all migrations applied).
// Don't edit by hand: change a migration, then regenerate. Overrides live in database.ts.

`
writeFileSync(TMP, note + readFileSync(TMP, 'utf8'))
renameSync(TMP, OUT)
console.log(`${OUT} updated`)
